### ISSUE TITLE
Sketch 58 Smart Layout

### ISSUE THREAD

**Issue by ziyafenn** [wousser/SketchExcelContentSync#3]
Hey there,
i tried the plugin with Sketch 58 and Smart Layout feature is not supported. Symbols are not auto-resized after the content update.

**Comment by wousser** [comment]
Thanks for reporting this issue.

I haven't updated to Sketch 58 yet, and not tried out Smart Layout feature. 

I'll take a look and see if I can support that.

**Comment by wousser** [comment]
Fixed in 0.6.0
