### ISSUE TITLE
location of generated file ? 

### ISSUE THREAD

**Issue by samuelacroix** [wousser/SketchExcelContentSync#5]
Hello, 

I tried to generate a content file but nothing happen when i click on button. 
Maybe the .xlsx fil is located somewhere in computer? 
How can i fix this issue? 
thx

**Comment by junaid2ali** [comment]
I use this plugin and its updated regularly https://www.contentsync.io/

**Comment by wousser** [comment]
> Hello,
> 
> I tried to generate a content file but nothing happen when i click on button. Maybe the .xlsx fil is located somewhere in computer? How can i fix this issue? thx

Fixed in latest version 0.4.1. File is stored in same directory as .sketch file.
