### ISSUE TITLE
One string overwriting all strings

### ISSUE THREAD

**Issue by royewest** [wousser/SketchExcelContentSync#9]
Hi Wouter,

When I create a content file using your plugin on the attached Sketch file and then sync and then pull the content back, one string overwrites all the other strings. Is this because I have all body text labeled #body? Am I doing something else wrong? Or...?

Thank you as always,

__Roy

P.S. As last time, I've changed the extension of my .sketch file to .PDF simply so Git would let me upload it. Please just restore .sketch extension to open it
[RoyWestTextExperiment.PDF](https://github.com/wousser/SketchExcelContentSync/files/8484491/RoyWestTextExperiment.PDF)
.

**Comment by wousser** [comment]
Thanks for your feedback.

Yes, all text layers in the Sketch Artboard have to be unique. One way to solve this is to rename your Text Layers Body1, Body2, etc.

I've published an update (version 0.8.0) which includes a check for duplicate Text Layers, and renames the layer if a duplicate is found. Please give it a try.

**Comment by royewest** [comment]
Thank you again, Wouter. I will experiment again with this helpful tool.
